### ISSUE TITLE
API strings from central server not localized

### ISSUE THREAD

**Issue by aronasorman** [fle-internal/ka-lite-central#171]
<a href="https://github.com/bcipolli"><img src="https://avatars.githubusercontent.com/u/4072455?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bcipolli](https://github.com/bcipolli)**
_Sunday Feb 16, 2014 at 01:05 GMT_
_Originally opened as https://github.com/learningequality/ka-lite/issues/1540_

---

The `khanload` app, for downloading KA data to a distributed server account, has code running on the central server (to download data via our private KA API key) that produces messages.  However, because the central server isn't running under that locale, those strings are not translated.

Solution:
1. Install all language pack strings on the central server.
2. Send current distributed server request language to the central server API
3. Wrap strings in `ugettext`

![image](https://f.cloud.github.com/assets/4072455/2179355/7a78ef46-96a6-11e3-91ad-33b215ff3051.png)

**Comment by arceduardvincent** [comment]
@aronasorman what branch does this issue used?
can you give the details and specifics on this issue,  I would like to work on this issue .

**Comment by arceduardvincent** [comment]
How I replicate:

1.Install the language pack strings on the central server `de`.
2. call the python manage.py languagepackdownload -l de --commandline to request the language pack in the central server
3. Try to replicate the messages. Example below

![screen shot 2015-02-19 at 3 45 46 pm](https://cloud.githubusercontent.com/assets/4099119/6263228/b8f504d8-b84e-11e4-99ae-cad9a42d95fc.png)

Todos: 
I will wrap the message with the ugettext.

**Comment by arceduardvincent** [comment]
Branch develop

Update: 
As I replicate the issue  the string was already wrap with ugettext _("string"). 
https://github.com/learningequality/ka-lite/blob/central-master/kalite/updates/api_views.py#L218
some sample api call from `/api/languagepacks/start`.

Image below demonstrate the following api calls the highlighted line and its response message string.
 
![screen shot 2015-02-20 at 2 56 58 pm](https://cloud.githubusercontent.com/assets/4099119/6282666/99e47112-b913-11e4-80c2-d5e476a3230f.png)

Todos : 
Make a dummy `.po` files for validation and test replication of message strings as suggested by @jamalex .

**Comment by arceduardvincent** [comment]
The image below show the translation string use for `fr` language pack.
![screen shot 2015-02-20 at 4 27 39 pm](https://cloud.githubusercontent.com/assets/4099119/6283312/aa030e50-b91d-11e4-8c87-b4d4ca05019a.png)

**Comment by arceduardvincent** [comment]
Some chat history from HipChat regarding this issue:
![screen shot 2015-02-23 at 6 25 05 pm](https://cloud.githubusercontent.com/assets/4099119/6326126/7146ef6e-bb89-11e4-93ca-8df2e4926c20.png)

I think this issue ok and the above problem is not manifested now.
The `dummy .po` files will be created in this issue #229
