### ISSUE TITLE
Error while registering account

### ISSUE THREAD

**Issue by MCGallaspy** [fle-internal/ka-lite-central#235]
On `http://staging.learningequality.org/accounts/register`, I tried to register an account. After filling out the form and submitting, I reached an error page. POST request to `/accounts/register/` got response 500.

**Comment by MCGallaspy** [comment]
Running a local instance of the central server doesn't have this issue...

**Comment by jamalex** [comment]
Should be fixed in https://github.com/learningequality/ka-lite/pull/3309 -- please re-open if testing proves otherwise.
