### ISSUE TITLE
Central server so ugly

### ISSUE THREAD

**Issue by MCGallaspy** [fle-internal/ka-lite-central#237]
There are just a bunch of small tweaks that need to be made on `develop`. Can someone just go through the site and make tweaks? See screenshots:
![ss](https://cloud.githubusercontent.com/assets/8888020/6586697/e843e4f4-c738-11e4-927e-07fa9ae24642.png)

There's probably more than this!

**Comment by jamalex** [comment]
By and large fixed in #242.
