### ISSUE TITLE
Padding is missing (?) on right-hand side of "Create org" button

### ISSUE THREAD

**Issue by jamalex** [fle-internal/ka-lite-central#243]
![image](https://cloud.githubusercontent.com/assets/618416/6719849/efff7576-cd7a-11e4-8b16-b614c7c46213.png)

Can you take a look, @66eli77?

**Comment by jamalex** [comment]
Other buttons seem to have the same issue:

![image](https://cloud.githubusercontent.com/assets/618416/6719896/5f3917d0-cd7b-11e4-9713-f943ed923a28.png)

![image](https://cloud.githubusercontent.com/assets/618416/6719903/70b5f348-cd7b-11e4-848a-cd4a704aa8c9.png)

Looks like they may just be fixed width? Also, they are styled differently (flatter) than buttons on other pages, e.g.:
![image](https://cloud.githubusercontent.com/assets/618416/6719923/95dd260a-cd7b-11e4-9c9d-88978ed0c7cd.png)

**Comment by jamalex** [comment]
Also, some alignment issues on the Go button:
![image](https://cloud.githubusercontent.com/assets/618416/6720191/b1ce1804-cd7d-11e4-9987-cceb0d051e18.png)

**Comment by jamalex** [comment]
And coach reports go off the edge:

![image](https://cloud.githubusercontent.com/assets/618416/6720288/e89cfd86-cd7e-11e4-99d5-702d2f472f30.png)

**Comment by jamalex** [comment]
Also, why is it using ID for the usernames there? Those users do actually have names...

**Comment by 66eli77** [comment]
I think we fixed the issues stated above, but when I check back at http://staging.learningequality.org/  it seems the issues reappear.
