### ISSUE TITLE
Error registering at http://staging.learningequality.org/accounts/register/

### ISSUE THREAD

**Issue by radinamatic** [fle-internal/ka-lite-central#245]
Steps to reproduce:

1. Go to http://staging.learningequality.org/
2. Choose "Sign up" from top-right options
3. Fill in the form and press the button "Register" 

![staging-register-error](https://cloud.githubusercontent.com/assets/1457929/6739227/b3231010-ce77-11e4-85fe-1bd23d61ec6d.png)

**Comment by jamalex** [comment]
Fixed in #246. Thanks for reporting!
