### ISSUE TITLE
facility end point returning 401

### ISSUE THREAD

**Issue by 66eli77** [fle-internal/ka-lite-central#247]
Branch: develop
Expected Behavior: show the progress report
Current Behavior: Redirect me to the login page even though I'm still logged in
Steps to reproduce:
1. login to staging central server as non super user
2. find a group and open its coach report
3. then it will redirect you to the login page

when on this page:  http://localhost:8000/coachreports/table/?prev=http%3A%2F%2Flocalhost%3A8000%2Fcoachreports%2Ftable%2F%3Fprev%3Dhttp%253A%252F%252Flocalhost%253A8000%252Fcoachreports%252Ftable%252F%253Fprev%253Dhttp%25253A%25252F%25252Flocalhost%25253A8000%25252Fcoachreports%25252Ftable%25252F%25253Fprev%25253Dhttp%2525253A%2525252F%2525252Flocalhost%2525253A8000%2525252Fcoachreports%2525252Ftable%2525252F%2525253Ffacility%2525253D09af1a5dcc4343b890b61ecb7e1cf93a%25252526group%2525253Dc45c98f7c84e47f3b092b848d6055d71

it try to make this api request:  http://localhost:8000/api/control_panel/facility/?_=1426814472971

and that will return the 401 UNAUTHORIZED

**Comment by MCGallaspy** [comment]
Super stale... but we should get someone testing the central server for 0.16.x for stuff like this.
