### ISSUE TITLE
0.14 language packs do not contain LC_MESSAGES folder (mo files... or rather, "no files")

### ISSUE THREAD

**Issue by jamalex** [fle-internal/ka-lite-central#262]
Translations for interface text/topic data is not showing up in 0.14 after downloading language packs.

Tracing this to the root cause, it looks like it's because the mo files aren't being distributed. For example, take a peek at: https://hub.learningequality.org/media/language_packs/0.14/es.zip

**Comment by aronasorman** [comment]
Working as of 09/08/2015.
