### ISSUE TITLE
Language packs take a long time to build, at 100% CPU

### ISSUE THREAD

**Issue by jamalex** [fle-internal/ka-lite-central#263]
Not sure which stage of the process is doing this, but the language pack building script takes a long time to run, and maxes out a core for the duration:

![image](https://cloud.githubusercontent.com/assets/618416/8349181/9ef16f16-1acf-11e5-9e8a-6a9024ec4ae8.png)

The 0.13 language packs built for at least 25 mins, when I last checked... probably over 30 mins.

Not urgent, but would be good to see whether this can be improved, if there's low-hanging fruit (since we build for every version every day).

**Comment by aronasorman** [comment]
Closing now, as future work now belongs to Studio's sushi chefs.
