### ISSUE TITLE
Central server coach reports are not very useful (since they only show recent data, and usage is likely to not be recent by the time it's synced and viewed)

### ISSUE THREAD

**Issue by jamalex** [fle-internal/ka-lite-central#269]
This seems like a pretty important issue for the distributed server, but even moreso for the central server.

Expected: User can view data from before the current week.

Observed: If no data in past week, report is useless.

![image](https://cloud.githubusercontent.com/assets/618416/8923131/c3ea53e6-34ba-11e5-9a0b-59dbe3d55ae9.png)

Also, some styling issues:
- What's supposed to be before the colon?
- Top bar overlaps
- Horizontal bar goes outside content area

**Comment by rtibbles** [comment]
Where is your Facility selector drop down, most importantly?

The name of the facility should be before the colon - but apparently you have no facilities (and yet have groups, confusingly).

The API endpoint already supports this, it should be as simple as reimplementing the time picker from the old coach reports. Can look into this on Wednesday.

**Comment by jamalex** [comment]
I believe this issue (as described) should be fixed, and is now superseded by https://github.com/fle-internal/ka-lite-central/issues/270
