### ISSUE TITLE
Can't log into to central server

### ISSUE THREAD

**Issue by mikewray** [fle-internal/ka-lite-central#276]
Hi Team! It's been while since I have been on the forum, missed you guys. This just a quickie, we cannot login into the central server http://kalite.learningequality.org/accounts/login/. The web page is available but you type in your credentials and it does not go anywhere. Have tried it across several browsers and users and same thing so pretty sure something your end. Would appreciate your attention to it...we trying to run our month end reports. Many thanks!

**Comment by jamalex** [comment]
@mikewray Could you try again? It looks like the Hub server may have run out of disk space this morning, but that was resolved, and I can log in currently.

**Comment by mikewray** [comment]
Sorted! Thanks Jamie. 

PS working with a professional camera guy this weekend, will get footage - got your notes. Have tried version 0.13.2, looks good but think going to hold out on version 0.12.10 till knowledge map available, as this is quite well used. We have got sponsorship for 3000 students - we getting KA Lite to some incredible places where it is so well needed. We have just signed an MOU with Children International and using there structure for distribution. Have put a good M&E process around what we doing (testing points using google forms) and given our foundational maths courses structure through designed playlists (web pages we have made that sit on the tablet and link to KA Lite) that link to the tests (certificates for each of this stages). This structure, together with our well trained coaches, is showing some amazing results. Introducing nutrition before class has improved things drastically. So in my silence I have been busy! So rest assured I'm still dedicated to the cause getting your most excellent product out there. By the way, there is big load shedding here...no power for 8 to 14 hours a day, so the offline off grid solution is proving its worth. We just looking at solar/battery solutions...we are just about to start testing something, if you have any intelligence/experience on this please let me know. Finally have recruited a local Zambian tech guy, showing promise. His name is Kapya and will introduce him to the forum. He will have lots of value to add. Hope all is well with you and the team.

**Comment by aronasorman** [comment]
Thanks for reporting this @mikewray!
