### ISSUE TITLE
Central server strings should not be included in PO files

### ISSUE THREAD

**Issue by jamalex** [fle-internal/ka-lite-central#278]
Hindi was recently translated to 100%, but dropped back down to a much lower percent. It looks like a lot of the new strings are from the central server:
https://crowdin.com/translate/ka-lite/28878/en-hi#
(e.g. "You have successfully removed %(username)s as an administrator for %(org_name)s", "Your personal views are your own, but in this case you are not allowed to delete yourself.")

As we have no forseeable plans to i18n-ize the central server, these strings should be removed ASAP, to avoid distracting translation efforts.

**Comment by aronasorman** [comment]
No longer included!
