### ISSUE TITLE
Central Server Reporting Not Working

### ISSUE THREAD

**Issue by mikewray** [fle-internal/ka-lite-central#285]
Hi team! I have noticed that the reports on the central server are not working for both student and group (and have not bee for a while). The student reports not working at all the group report partially working but not providing all the data.  The data has been generated from version 12 instance of kalite. 

**Student Report:** click on the coach button for a student you get the following:
![cs student report](https://cloud.githubusercontent.com/assets/7093712/11346051/66e8107c-9223-11e5-838b-8483d54a1234.png)

**Group Report:** you select a date range and data that come backs is incomplete - there are hours but no exercises done etc which is obviously not the case. 
![cs group report](https://cloud.githubusercontent.com/assets/7093712/11346226/479215be-9224-11e5-9a24-edf8690f5d17.png)

**Comment by benjaoming** [comment]
Hi @mikewray - I'm aware that this response is 4 years due. I'm responding now to sort out the state of affairs. Better now than never, I hope.

Let me know if you have any questions at this stage or whether anything related to KA Lite is relevant anymore? I'd be happy to seek solutions.

I was reviewing what is functional on the Central Server. It seems that those nice circles in your screenshot don't show up anymore (although the code to do so is in place, the circles are not showing and there's no error messages).

But I do find the coach reports with some kind of data in it:

https://kalite.learningequality.org/coachreports/coach/zone/1c9055ccdda24937ab531c3343a90b2d/69044245febd43a394acc739edd47279/

My immediate concern would be that coach reports aren't really useful anymore.

I'm suggesting to pin all this as a Known Issue:

* While the Coach Report tool on the Central Server remains in place, the links to it have been removed. Generating Coach Reports should be done in local instances of Kolibri. If you require reports of aggregated data sets, use the Central Server's CSV Export function.
