### ISSUE TITLE
Validate the instructions at the README.md file.

### ISSUE THREAD

**Issue by cpauya** [fle-internal/ka-lite-central#299]
Branch: `develop`

It's been a really long time, so it's understandable that the instructions in the `develop:ka-lite-central\README.md` file are either confusing, outdated, or are not applicable anymore.  The Markdown formatting is also broken.

Let's fix the formatting, validate, simplify, then update the instructions there.

**Comment by benjaoming** [comment]
Yes, I find that writing down the steps (as a README) is also mostly the first step towards implementing a Docker configuration.

**Comment by aronasorman** [comment]
Good idea!

**Comment by benjaoming** [comment]
@indirectlylit - this isn't KA Lite, though... it's the "central server", which is quite a hack.

**Comment by indirectlylit** [comment]
ah my bad

**Comment by benjaoming** [comment]
I would feel a bit sorry for @jredrejo, if he was to start his KA Lite learning from this repo :smile:

**Comment by benjaoming** [comment]
@jredrejo if you haven't already, try to install it by following the official docs: https://ka-lite.readthedocs.io/en/latest/installguide/install_main.html

I don't think this is useful, but it will give you more insights: You could try to get the development environment up and running. It's not thaaat difficult, but the nodejs version will IIRC interfere with your kolibri nodejs.

**Comment by cpauya** [comment]
Update: 

The on-going hotfix branch at https://github.com/mrpau/ka-lite-central/tree/hotfix/299-validate-readme-file#environment-setup-using-vagrant now has updated instructions on how to make KA Central run in a Vagrant box. 

It still has the `ImportError: cannot import name VideoLogResource` error but at least it's now  running under Nginx and UWSGI in an isolated virtual box.  See attached image of the error.

![screenshot 2019-01-07 16 45 43](https://user-images.githubusercontent.com/175580/50758106-2cf59180-129c-11e9-8382-841f1499169b.png)

**Comment by benjaoming** [comment]
I put asset building into Docker, the rest is now very conventional. And the Git submodule is dead.

**Comment by indirectlylit** [comment]
death to git submodules
