### ISSUE TITLE
Signing Up should not accept an Invalid Country Name

### ISSUE THREAD

**Issue by codemania113** [fle-internal/ka-lite-central#83]
Branch: nalanda-rct1

Current Behavior: In Signing Up page, there is adding organization details option is present. It has field for Organization Country which accepts invalid country names too.

Expected Behavior: Invalid country names  should not be accepted.

Steps to Reproduce:

1. Open the Sign Up page
2. Go to "Add organization details"
3. Enter any invalid country name
![screenshot from 2014-04-08 15 12 51](https://cloud.githubusercontent.com/assets/6392747/2642144/ffc533fa-bf03-11e3-94c0-c3805add0582.png)

**Comment by jamalex** [comment]
Enforcing this is a big task, given the variability in spelling/naming/formatting of country names. We can add our own logic for grouping entries here post-hoc, for analysis.
